# Generated by Django 2.1.2 on 2019-02-11 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('type', models.CharField(choices=[('D', 'Digital'), ('HH', 'High High'), ('H', 'High'), ('L', 'Low'), ('LL', 'Low Low')], default='D', max_length=32)),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'Critical'), (2, 'High'), (3, 'Medium'), (4, 'Low')], default=4)),
                ('refObject', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DigitalIO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('type', models.CharField(choices=[('INPUT', 'Input'), ('OUTPUT', 'Output')], max_length=32)),
                ('on_description', models.CharField(default='On', max_length=100)),
                ('off_description', models.CharField(default='Off', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Digital IO',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('revision', models.FloatField(default=-1.0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='', max_length=500)),
                ('order', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Document Entries',
            },
        ),
        migrations.CreateModel(
            name='DocumentSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('hierarchy', models.PositiveSmallIntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4')])),
                ('order', models.PositiveIntegerField()),
                ('section_number', models.CharField(max_length=32)),
                ('assigned_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.Document')),
                ('assigned_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tables.DocumentSection')),
            ],
            options={
                'verbose_name_plural': 'Document Sections',
            },
        ),
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CUSTOM', 'Custom'), ('FLT', 'Fault'), ('ON', 'On'), ('OFF', 'Off'), ('HH', 'High High'), ('H', 'High'), ('L', 'Low'), ('LL', 'Low Low'), ('FAIL_TO_START', 'Fail to Start'), ('FAIL_TO_STOP', 'Fail to Stop'), ('FAIL_TO_OPEN', 'Fail to Open'), ('FAIL_TO_CLOSE', 'Fail to Close'), ('FBK_FAIL', 'Feedback Fail'), ('COM_FAIL', 'Communications Fail')], default='ON', max_length=200)),
                ('alarm_enable', models.BooleanField(default=False)),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'Critical'), (2, 'High'), (3, 'Medium'), (4, 'Low')], default=4)),
            ],
        ),
        migrations.CreateModel(
            name='IndexTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.CharField(max_length=32)),
                ('tag', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('io_allocation', models.CharField(blank=True, default='', max_length=100)),
                ('cabinet', models.CharField(blank=True, default='', max_length=100)),
                ('pid_doc', models.CharField(blank=True, default='', max_length=500)),
                ('schematic_doc', models.CharField(blank=True, default='', max_length=500)),
                ('termination_doc', models.CharField(blank=True, default='', max_length=500)),
                ('index_tag', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tables.IndexTag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='indextag',
            unique_together={('table', 'tag')},
        ),
        migrations.AddField(
            model_name='documentsection',
            name='index_tag',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tables.IndexTag'),
        ),
        migrations.AddField(
            model_name='documententry',
            name='assigned_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.DocumentSection'),
        ),
        migrations.AddField(
            model_name='document',
            name='index_tag',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tables.IndexTag'),
        ),
        migrations.AddField(
            model_name='digitalio',
            name='index_tag',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tables.IndexTag'),
        ),
    ]
