# Generated by Django 2.1.2 on 2019-02-10 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('type', models.CharField(choices=[('D', 'Digital'), ('HH', 'High High'), ('H', 'High'), ('L', 'Low'), ('LL', 'Low Low')], default='D', max_length=32)),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'Critical'), (2, 'High'), (3, 'Medium'), (4, 'Low')], default=4)),
                ('refObject', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CtrlObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('type', models.CharField(choices=[('DI', 'Digital Input'), ('DO', 'Digital Output'), ('AI', 'Analog Input'), ('AO', 'Analog Output'), ('DRiVE', 'Drive'), ('VALVE', 'Valve')], max_length=32)),
            ],
            options={
                'verbose_name_plural': 'Control Objects',
            },
        ),
        migrations.CreateModel(
            name='DigitalIO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('type', models.CharField(choices=[('DO', 'Digital Output'), ('DI', 'Digital Input')], default='DI', max_length=32)),
                ('on_description', models.CharField(default='On', max_length=100)),
                ('off_description', models.CharField(default='Off', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Digital IO',
            },
        ),
        migrations.CreateModel(
            name='DocumentEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, unique=True)),
                ('text', models.CharField(blank=True, default='', max_length=500)),
                ('order', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Document Entries',
            },
        ),
        migrations.CreateModel(
            name='DocumentSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('hierarchy', models.PositiveSmallIntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4')])),
                ('order', models.PositiveIntegerField(unique=True)),
                ('section_number', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': 'Document Sections',
            },
        ),
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('io_allocation', models.CharField(blank=True, default='', max_length=100)),
                ('cabinet', models.CharField(blank=True, default='', max_length=100)),
                ('pid_doc', models.CharField(blank=True, default='', max_length=500)),
                ('schematic_doc', models.CharField(blank=True, default='', max_length=500)),
                ('termination_doc', models.CharField(blank=True, default='', max_length=500)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.CtrlObject')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('type', models.CharField(choices=[('DOC', 'Document'), ('DOC_SEC', 'Document Section'), ('DOC_TEXT', 'Document Text'), ('DI', 'Digital Input'), ('DO', 'Digital Output'), ('AI', 'Analog Input'), ('AO', 'Analog Output'), ('DI_COMM', 'Digital Input via Communications'), ('DO_COMM', 'Digital Output via Communications'), ('AI_COMM', 'Analog Input via Communications'), ('AO_COMM', 'Analog Output via Communications'), ('EVENT', 'Event'), ('INTERLOCK', 'Interlock'), ('DRiVE', 'Drive'), ('VALVE', 'Valve'), ('CABINET', 'Cabinet')], max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('tag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tables.Tag')),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('revision', models.FloatField(default=-1.0)),
            ],
        ),
        migrations.AddField(
            model_name='documententry',
            name='assigned_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.DocumentSection'),
        ),
        migrations.AddField(
            model_name='documentsection',
            name='assigned_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.Document'),
        ),
    ]
