# Generated by Django 2.1.2 on 2018-11-21 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_auto_20181121_0321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrument',
            name='doc_ref',
        ),
    ]
